### ISSUE TITLE
Add :doitfaggot:

### ISSUE THREAD

**Issue by ZhangC1459** [SpinnerMaster/DIX-Standard-Emote-Pack#8]
:doitfaggot:

![image](https://cloud.githubusercontent.com/assets/8743822/10151529/7201ee58-6616-11e5-8d6b-d1088602d8db.png)

Also :killyourself: or :biomass:

![image](https://cloud.githubusercontent.com/assets/8743822/10151566/cf019d88-6616-11e5-99a8-bcb86c7146cb.png)

**Comment by SpinnerMaster** [comment]
Ill add :doitfaggot: but I need something a bit higher quality for :killyourself:

**Comment by ZhangC1459** [comment]
I'll get on it later when i'm not at work
